name: Funn
description: Registrer ett nytt funn i innsiktsdatabasen
title: " "
labels: ["Type / funn"]
body:
  - type: markdown
    attributes:
      value: |
        Takk for at du bidrar til økt kunnskapsdeling på tvers av det offentlig!

  - type: textarea
    id: description
    attributes:
      label: Beskriv funnet
      description:  Gi en kort beskrivelse av funnet
      placeholder: F.eks, Uforventede pop-ups kan skape usikkerhet og flere forveksler de med reklame, annonser eller svindel.
    validations:
      required: true

  - type: dropdown
    id: type-funn
    attributes:
      label: Hva slags funn er det
      description: Er det et informativt eller handlingsrettet funn?
      options:
        - Informativ
        - Handlingsrettet
        - Usikker
    validations:
      required: true

  - type: textarea
    id: where
    attributes:
      label: Hvor oppstod funnet
      description: Skriv ned hvor funnet fant sted
      placeholder: F.eks, På hjemsiden til Altinn.no
    validations:
      required: true

  - type: textarea
    id: who
    attributes:
      label: Hvem kommer funnet fra
      description: Hvem/hvilken gruppe er kilden til funnet?
      placeholder: F.eks, ikke-digitale og eldre med lav digital kompetanse
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Eksempler
      description: Bruk eksempler for å forklare funnet ytterligere
      placeholder: F.eks, vedlagt bilde viser ulike typer pop-ups som ofte forveksles
    validations:
      required: true

  - type: textarea
    id: relevant-research
    attributes:
      label: Relevant forskning
      description: Link til studien funnet stammer ifra
      placeholder: F.eks, et Github issue, en rapport eller andre typer artefakter
      value: "- Dette funnet er del av #1"
    validations:
      required: true

  - type: textarea
    id: relevant-insight
    attributes:
      label: Relevant innsikt
      description: Link til innsikt der funnet brukes
      placeholder: F.eks, et Github issue med tittel som starter med [Innsikt]
    validations:
      required: false