name: Innsikt
description: Registrer innsikt i innsiktsdatabasen
title: "[Innsikt]: "
labels: ["Type / innsikt"]
body:
  - type: markdown
    attributes:
      value: |
        Takk for at du bidrar til økt kunnskapsdeling på tvers av det offentlig!

  - type: textarea
    id: description
    attributes:
      label: Beskriv innsikten
      description: Gi en kort beskrivelse av innsikten
      placeholder: F.eks, Uforventede pop-ups kan skape usikkerhet og flere forveksler de med reklame, annonser eller svindel.
    validations:
      required: true

  - type: dropdown
    id: type-innsikt
    attributes:
      label: Hva slags innsikt er det
      description: Er det informativ eller handlingsrettet innsikt?
      options:
        - Informative
        - Actionable
    validations:
      required: true

  - type: textarea
    id: relevant-findings
    attributes:
      label: Hvilke funn er innsikten bygget på?
      description: Link til funnene innsikten bygger på
      placeholder: F.eks, github issue
      value: |
        Denne innsikten er bygget på:
        - #1 
        - #2
      render: bash
    validations:
      required: true

  - type: textarea
    id: recommendations
    attributes:
      label: Anbefalinger / Muligheter
      description: Hvilke muligheter gir innsikten og hva anbefaler du
      placeholder: F.eks, en kort tekst om muligheter fra innsikten samt en liste med anbefalinger
    validations:
      required: true