name: Forskningsutfall
description: Registrer et forskningsutfall i innsiktsdatabasen
title: "[Utfall]: "
body:
  - type: markdown
    attributes:
      value: |
        Takk for at du bidrar til økt kunnskapsdeling på tvers av det offentlig!

  - type: textarea
    id: what
    attributes:
      label: Hva
      description: Beskriv funnet
      placeholder: F.eks, Uforventede pop-ups kan skape usikkerhet og flere forveksler de med reklame, annonser eller svindel.
    validations:
      required: true

  - type: textarea
    id: where
    attributes:
      label: Hvor
      description: Skriv ned hvor funnet fant sted
      placeholder: F.eks, På hjemsiden til Altinn.no
    validations:
      required: true

  - type: textarea
    id: who
    attributes:
      label: Hvem
      description: Hvem kommer funnet fra eller hva er kilden til funnet?
      placeholder: F.eks, ikke-digitale og eldre med lav digital kompetanse
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Eksempler
      description: Bruk eksempler for å forklare funnet ytterligere
      placeholder: F.eks, vedlagt bilde viser ulike typer pop-ups som ofte forveksles
    validations:
      required: true

  - type: textarea
    id: relevant-research
    attributes:
      label: Relevant forskning
      description: Link til studien funnet stammer ifra
      placeholder: F.eks, et Github issue, en rapport eller andre typer artefakter
    validations:
      required: true

  - type: textarea
    id: relevant-insight
    attributes:
      label: Relevant innsikt
      description: Link til innsikt der funnet brukes
      placeholder: F.eks, et Github issue med tittel som starter med [Innsikt]
    validations:
      required: true
  

  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
    validations:
      required: true