name: Forskningsutfall
description: Registrer et forskningsutfall i innsiktsdatabasen
title: "[Utfall]: "
label: "[Sample size/]:"
  - type: dropdown
    attributes:
      label: Antall brukere
      description: Hvor mange brukere var involvert i studien?
      multiple: true
      options:
        - 10-20
        - 20-40
    validations:
      required: true
      
body:
  - type: markdown
    attributes:
      value: |
        Takk for at du bidrar til økt kunnskapsdeling på tvers av det offentlig!

  - type: textarea
    id: what
    attributes:
      label: Hva
      description: Beskriv funnet
      placeholder: F.eks, Uforventede pop-ups kan skape usikkerhet og flere forveksler de med reklame, annonser eller svindel.
    validations:
      required: false

  - type: textarea
    id: where
    attributes:
      label: Hvor
      description: Skriv ned hvor funnet fant sted
      placeholder: F.eks, På hjemsiden til Altinn.no
    validations:
      required: false

  - type: textarea
    id: who
    attributes:
      label: Hvem
      description: Hvem kommer funnet fra eller hva er kilden til funnet?
      placeholder: F.eks, ikke-digitale og eldre med lav digital kompetanse
    validations:
      required: false

  - type: textarea
    id: examples
    attributes:
      label: Eksempler
      description: Bruk eksempler for å forklare funnet ytterligere
      placeholder: F.eks, vedlagt bilde viser ulike typer pop-ups som ofte forveksles
    validations:
      required: false

  - type: textarea
    id: relevant-research
    attributes:
      label: Relevant forskning
      description: Link til studien funnet stammer ifra
      placeholder: F.eks, et Github issue, en rapport eller andre typer artefakter
    validations:
      required: false

  - type: textarea
    id: relevant-insight
    attributes:
      label: Relevant innsikt
      description: Link til innsikt der funnet brukes
      placeholder: F.eks, et Github issue med tittel som starter med [Innsikt]
    validations:
      required: false
  
  - type: dropdown
    id: media-format
    attributes:
      label: Media format
      description: Hvilket format har studien du linker til?
      options:
        - Ikke publisert
        - Rapport (nettbasert)
        - Rapport (PDF)
        - Rapport (Presentasjon)
        - Github issue
        - Dokumentasjon (nettbasert)
        - Annen type artefakt
    validations:
      required: true

  - type: dropdown
    id: available-languages
    attributes:
      label: Tilgjengelig på språk
      description: Hvilke språk er studien tilgjengelig på? (du kan velge flere)
      multiple: true
      options:
        - Deutsch / Tysk
        - English / Engelsk
        - Español / Spansk
        - François / Fransk
        - Norsk (bokmål)
        - Norsk (nynorsk)
        - Sámi / Samisk
        - Tigrinya / Tigrinya
    validations:
      required: true