name: Forskningsutfall
description: Registrer et forskningsutfall i innsiktsdatabasen
title: "[Qx/202x]: "
labels: ["Type / utfall"]
body:
  - type: markdown
    attributes:
      value: |
        Takk for at du bidrar til økt kunnskapsdeling på tvers av det offentlig!

- type: checkboxes
  id: date
  attributes:
    label: Når ble studien ferdigstilt?
    description: Sett dato for publisering i tittelen med kvartal etterfulgt av årstall (Q3-2021).
    options:
      - label: Jeg har satt dato i tittelen

  - type: textarea
    id: description
    attributes:
      label: Beskriv studien
      description: Gi en kort beskrivelse av hva studien gikk ut på
      placeholder: F.eks, ...
    validations:
      required: false
  
  - type: dropdown
    id: media-format
    attributes:
      label: Media format
      description: Hvilket format har studien du linker til?
      options:
        - Ikke publisert
        - Rapport (nettbasert)
        - Rapport (PDF)
        - Rapport (Presentasjon)
        - Github issue
        - Dokumentasjon (nettbasert)
        - Annen type artefakt
    validations:
      required: true

  - type: dropdown
    id: research-methods
    attributes:
      label: Forskningsmetoder
      description: Hvilke forskningsmetoder ble brukt i studien?
      multiple: true
      options:
        - Archival research
        - Conceptual test
        - Probe (cultural / technical)
        - Ethnography
        - Focus group
        - Literature review
        - Observation
        - Service safari
        - Survey
        - Usability test
        - Desk research
        - Interview
        - Annet
    validations:
      required: true

  - type: textarea
    id: sample-size
    attributes:
      label: Antall studiedeltagere
      description: Skriv inn antall deltagere/brukere som tok del i studien
      placeholder: F.eks, 20
    validations:
      required: true

  - type: textarea
    id: keywords
    attributes:
      label: Nøkkelord
      description: Fyll inn nøkkelord for studien med små bokstaver og separert med komma
      placeholder: F.eks, pensjon, velferd, nav
    validations:
      required: false

  - type: textarea
    id: owner
    attributes:
      label: Hvem eier studien
      description: Skriv navnet på organisasjonen(e) som eier resultatet fra studien
      placeholder: F.eks, NAV, Skatteetaten, Digitaliseringsdirektoratet, Brønnøysundsregistrene
    validations:
      required: false

  - type: dropdown
    id: available-languages
    attributes:
      label: Tilgjengelig på språk
      description: Hvilke språk er studien tilgjengelig på? (du kan velge flere)
      multiple: true
      options:
        - English / Engelsk
        - Norsk (bokmål)
        - Norsk (nynorsk)
        - Sámi / Samisk
    validations:
      required: true

  - type: textarea
    id: source
    attributes:
      label: Link til studien
      description: Legg inn link (url) til studien
      placeholder: F.eks, https://www.digdir.no/datadeling/innsynslosning-tekniske-og-juridiske-muligheter/3465
    validations:
      required: true